dataset: cifar10
num_classes: 10
img_size: 32
mean:
    - 0.4914
    - 0.4822
    - 0.4465
std:
    - 0.2470
    - 0.2435
    - 0.2616
crop_pct: 01.0
scale:
    - 0.8
    - 01.0
interpolation: bicubic
train_interpolation: random
aa: rand-m9-mstd0.5-inc1
mixup: 0.8
mixup_off_epoch: 0
mixup_prob: 01.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 01.0
reprob: 0.25
remode: pixel
amp: True
model: cct_7_3x1_32_sine
model_ema: False
batch_size: 128
lr: 5e-4
min_lr: 1e-5
sched: cosine
weight_decay: 5e-2
epochs: 1500
cooldown_epochs: 10
warmup_epochs: 10
warmup_lr: 0.00001
opt: adamw
smoothing: 0.01
workers: 8